{% set name = "better-setuptools-git-version" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/better-setuptools-git-version-{{ version }}.tar.gz
  sha256: 2e0d70cbd3287d3fbe8696057f3c870d937fd9fbdd4a57d1a15796553b17d387

build:
  entry_points:
    - better-setuptools-git-version = better_setuptools_git_version:get_version
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=8.0

test:
  imports:
    - better_setuptools_git_version
  commands:
    - pip check
    # The CLI has no help options and thus fails
    # - better-setuptools-git-version --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vivin/better-setuptools-git-version
  summary: Automatically set package version using git tags.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
